name: Consolidate Metadata

on:
  workflow_call:

jobs:
  consolidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
        with:
          python-version: '3.13'

      - name: Run consolidation script
        run: python scripts/consolidate_metadata.py

      - name: Commit changes and make PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="automation/consolidate-metadata"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Update aggregated metadata for each plugin" || echo "No changes to commit"
          git push origin "$BRANCH_NAME" --force
          gh pr create --title "chore(consolidate): Update aggregated metadata for each plugin" \
             --body "This PR automatically updates aggregated metadata for each plugin." \
             --head "$BRANCH_NAME" \
             --base main || \
          gh pr edit "$BRANCH_NAME" \
           --title "chore(consolidate): Update aggregated metadata for each plugin" \
           --body "This PR automatically updates aggregated metadata for each plugin."
